global:
  scrape_interval: "60s"

scrape_configs:
  - job_name: "prometheus"
    target_groups:
    - targets:
        - "localhost:9090"
  - job_name: "node-eulenmap1"
    target_groups:
    - targets:
        - "localhost:9100"
